// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNezrwFx6PmmV-vptEXykMZtOaEBSyFPw',
    appId: '1:716391688865:web:69fa375aeae04e24275ee0',
    messagingSenderId: '716391688865',
    projectId: 'medical-test-report',
    authDomain: 'medical-test-report.firebaseapp.com',
    databaseURL: 'https://medical-test-report.firebaseio.com',
    storageBucket: 'medical-test-report.appspot.com',
    measurementId: 'G-51BYH896QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6t8Fv2tklufPc-GtYgaOHcjAWmVTpZU',
    appId: '1:716391688865:android:fad24ea5745868ba275ee0',
    messagingSenderId: '716391688865',
    projectId: 'medical-test-report',
    databaseURL: 'https://medical-test-report.firebaseio.com',
    storageBucket: 'medical-test-report.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDwkDaJS6dii35LvkrU8e2s5uZHIVlG78',
    appId: '1:716391688865:ios:baf3169d4f6ec41a275ee0',
    messagingSenderId: '716391688865',
    projectId: 'medical-test-report',
    databaseURL: 'https://medical-test-report.firebaseio.com',
    storageBucket: 'medical-test-report.appspot.com',
    androidClientId: '716391688865-k7fgeq76ftsiv177c78svue0psgastae.apps.googleusercontent.com',
    iosClientId: '716391688865-5tidku281gv0hf69c8if61q8fqt9ii09.apps.googleusercontent.com',
    iosBundleId: 'com.medicaltestpriceappbd.medicaltestpriceappbd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDwkDaJS6dii35LvkrU8e2s5uZHIVlG78',
    appId: '1:716391688865:ios:baf3169d4f6ec41a275ee0',
    messagingSenderId: '716391688865',
    projectId: 'medical-test-report',
    databaseURL: 'https://medical-test-report.firebaseio.com',
    storageBucket: 'medical-test-report.appspot.com',
    androidClientId: '716391688865-k7fgeq76ftsiv177c78svue0psgastae.apps.googleusercontent.com',
    iosClientId: '716391688865-5tidku281gv0hf69c8if61q8fqt9ii09.apps.googleusercontent.com',
    iosBundleId: 'com.medicaltestpriceappbd.medicaltestpriceappbd',
  );
}
